### ISSUE TITLE
Feature request : permission checks

### ISSUE THREAD

**Issue by DrYak** [CODeRUS/aliendalvik-control#2]
Hello !

Currently, Sailfish seems to be still [afflicted by this usability bug/security feature](https://together.jolla.com/question/167725/files-received-over-bluetooth-have-too-strict-permissions/), which leads to users [still not being able to open pictures received over bluetooth using Android apps](https://together.jolla.com/question/188664/shared-bluetooth-pictures-not-available-in-android-apps/).

That's due to Sailfish trying to make things a bit more secure by not systematically making the received files world-readable, (they're `0640` instead of `0644`) combined with Android trying to be secure by giving each apps its own UID:GID. Thus app can't immediately open files received over Bluetooth (you would need to first chmod them from the cli or from your favourite file manager).

Do you think if it would be a nice feature if the plug-in's empty screen where you swipe to trigger the sharing (the empty screen, with the top right "*Share to Android*" tab-trigger), has in-tab text that reports if the file is world readable, and offers a button to change permissions before the user right-swipes ?

That would be - I would thing - a nice features :
 - that works around the current Sailfish usability bug/security feature 
 - that would do a useful check due to Android UID:GID based security.

Thank you for your wonderful work.

**Comment by CODeRUS** [comment]
Please check with 9.0.6 version
