### ISSUE TITLE
[Regression] "Toggle Android navbar" is invisible and non-functional on SFOS 2

### ISSUE THREAD

**Issue by Olf0** [CODeRUS/aliendalvik-control#3]
Although "Toggle Android navbar" of **Aliendalvik control** 1.2.2 is selectable (with new icon) as an Eventsview shortcut (in *Settings -> Events view -> Select shortcuts*), it invisible and non-functional in the Eventsview proper on SFOS 2.
In contrast to that it is properly displayed and works fine in the Top Menu of SFOS 3.
The "Toggle Android navbar" was working fine in previous **Aliendalvik control** versions (below 1.2) under SFOS 2.

Tested on a Jolla 1 phone with SFOS 2.2.1.18 (and counter-tested on an Xperia X with SFOS 3.0.1.11).

P.S. (related issue): Please also restore the old "Toggle Android navbar" **icon** in the **Aliendalvik control** branch for the AOSP 4.x based Android runtime environment, as the new icon does not resemble the actual navigation bar button icon (of Android 4.x) at all.

**Comment by CODeRUS** [comment]
this is somewhat complicated. sfos 2 toggles are unusable in sfos3, and vise versa :D

**Comment by Olf0** [comment]
Thanks for the quick reply.
Shall I downgrade to **Aliendalvik control** 1.1.0 under SailfishOS 2.2.1 and you update the spec file of v1.2.x to require sailfish-version >= 3.0.0.0?

P.S.: Nevertheless the new navbar icon is "wrong" for the AOSP 4.x based AlienDalvik (under SailfishOS 3 or not), while the previous icon (in v1.1.0) was fine: Please revert this change.

**Comment by Olf0** [comment]
O.K. v1.2.3 is working fine under SFOS 2, v1.2.4 depends on SFOS 3.
Hence closing.
