### ISSUE TITLE
Open URL issues

### ISSUE THREAD

**Issue by null-von-sushi** [CODeRUS/aliendalvik-control#4]
Open Android URL just plain doesn't work. 
Open Android URL Selector does work, but only if the browser has been started before, it can not launch the browser and open the URL in it.

EDIT: for some reason 'Android Open URL' now also behaves like 'Open Android URL selector' except it DOES open firefox on the correct page even if firefox wasn't running before?
 
Is there any way to just get it to open Firefox reliably, without any pop-ups?

**Comment by CODeRUS** [comment]
Can you please tell what device you have and what version of ad control you using?)

**Comment by null-von-sushi** [comment]
Sure.
XA2 (H3113 I think?)
AD Control doesn't list a version in the program, but `pkcon` says `aliendalvik-control-9.0.1-1.armv7hl`

**Comment by CODeRUS** [comment]
Okay, seems open android url is broken indeed :(

**Comment by CODeRUS** [comment]
Fixed in 9.0.3
