### ISSUE TITLE
Interoperability of AlienDalvik Control 9 with Patch: Back-button gesture for Android

### ISSUE THREAD

**Issue by Olf0** [CODeRUS/aliendalvik-control#5]
Filing this issue here in order not to be forgotten:
http://talk.maemo.org/showthread.php?p=1556221
It was quite nice to gain that additional screen space, so please check, if the suspicion is true, and fix AlienDalvik-control, if necessary.
Thanks!

**Comment by CODeRUS** [comment]
as stated in release notes: ad control now living on system dbus, so patch should be updated accordingly

**Comment by Olf0** [comment]
Thank you very much for resurrecting the old API in [Aliendalvik-control 9.0.4](https://github.com/CODeRUS/aliendalvik-control/releases/tag/9.0.4) (rsp. [commit 122e05c](https://github.com/CODeRUS/aliendalvik-control/commit/122e05c795a244b7d0a7310b679548894d98cd29)). 😁
You really made my day and saved me from writing a rant about deliberately breaking APIs used by dependent software (which is so Jolla style 😒): The "Patch: Back-button gesture for Android" is working fine, again.
