### ISSUE TITLE
App opens a second time when using new onehand control

### ISSUE THREAD

**Issue by donni106** [CODeRUS/aliendalvik-control#6]
When using the new feature onehand control on my XA2 with Sailfish 3.0.3.9, the current Android app opens again. The app then appears twice on the home screen - same app, two cards.
It happens not every time, but very often. It is reproducible with normal usage of the onehand control or by simply tapping on the new right bar.

**Comment by CODeRUS** [comment]
Explain please. I can't understand what is the problem currently. Make a video if possible.

**Comment by donni106** [comment]
Ok. Is there a Sailfish Screen Recording Tool? I cannot find anything.
So I think I need to record it with a second device.

**Comment by CODeRUS** [comment]
https://openrepos.net/content/coderus/screenrecorder here you go

**Comment by donni106** [comment]
Ok, here it is (after recorded an avi file, made a mp4 file, to make the gif for GitHub):
![screenrecorder-04-07-19_11-49-25 2019-07-04 12_34_53](https://user-images.githubusercontent.com/1942953/60660469-22394500-9e58-11e9-8693-3834924a17ad.gif)

Steps you see:
1. opening Store app
2. using onehand control
3. Store app opens a second time
4. closing second Store app
5. opening Store app
6. tapping on the onehand control right bar
7. Store app opens a second time

This is not related to the Store app. It happens also with other Android apps.

Do you understand now?
I don't know if it is a problem with the onehand control or with my phone in general.

**Comment by CODeRUS** [comment]
Well, you can try to check if it happens after reboot.
Also remove aliendalvik control and check if it still happens, i cant reproduce it for myself.

**Comment by donni106** [comment]
> Well, you can try to check if it happens after reboot.

Ok I will later.

> Also remove aliendalvik control and check if it still happens, i cant reproduce it for myself.

Ähm..but if I remove that, I have no onehand control either!? Or did I understand something wrong?

**Comment by CODeRUS** [comment]
TO check this is general problem not caused by aliendalvik control

**Comment by donni106** [comment]
> Well, you can try to check if it happens after reboot.

It is happening in the same way directly after reboot with the first Android app used.
