### ISSUE TITLE
9.3.0 should be packed just for SFOS 3.4 (or higher) for Storeman Users

### ISSUE THREAD

**Issue by Bsoupe** [CODeRUS/aliendalvik-control#9]
RPM/Zypper packaging should get an update so that Storeman shows this update just on devices with 3.4 installed. Thanks & kind regards!

**Comment by Bsoupe** [comment]
Tipp by Thaodan: https://gitlab.com/Thaodan/sailfishos-patch-base-makefile/-/blob/master/template.spec#L16

**Comment by CODeRUS** [comment]
Why? It is fully usable on previous versions

**Comment by Bsoupe** [comment]
I had an error message on a XA2 Plus coming form 3.3. I try to reproduce it....

**Comment by CODeRUS** [comment]
there was a faulty build published to openrepos. try with recent rpm file

**Comment by Bsoupe** [comment]
Now I've 9.3.0.2 on SFOS 3.3 thanks. I'm an EA user but I wait a little.

**Comment by Bsoupe** [comment]
![photo_2020-09-30_10-52-53](https://user-images.githubusercontent.com/71604971/94664611-5de8e600-030b-11eb-85cb-222c4dc79d84.jpg)
I tried to uninstall AD Control and received attached message, that is nearly similar to the message during installation1
"Ein Fehler ist aufgetreten" means "an error occurred!

**Comment by CODeRUS** [comment]
please post it to storeman. it's not relevant to application

**Comment by Bsoupe** [comment]
Yes, thats plausible i will do so thanks!
